nanoGPT Training Log

Start of training: [Insert date and time here]


iter 570: loss 1.5513, time 6645.91ms
iter 580: loss 1.5312, time 4882.27ms
iter 590: loss 1.5060, time 5004.08ms
iter 600: loss 1.5596, time 5077.27ms
iter 610: loss 1.5414, time 4769.89ms
iter 620: loss 1.4780, time 5044.66ms
iter 630: loss 1.5005, time 6233.37ms
iter 640: loss 1.5036, time 5732.75ms
iter 650: loss 1.5172, time 4873.60ms
iter 660: loss 1.5012, time 5787.53ms
iter 670: loss 1.4761, time 6093.42ms
iter 680: loss 1.4484, time 5290.22ms
iter 690: loss 1.4734, time 5554.68ms
iter 700: loss 1.4984, time 5915.95ms
...
[Continue pasting all iterations up to the end]
...
iter 1990: loss 1.1595, time 6421.62ms
step 2000: train loss 1.0566, val loss 1.4761
iter 2000: loss 1.1553, time 536208.67ms
iter 2010: loss 1.1500, time 12170.52ms
iter 2020: loss 1.1522, time 14827.96ms

[Paste the full error traceback here]
^CTraceback (most recent call last):
  File "/Users/deepaklenka/sakana/AI-Scientist/templates/nanoGPT/experiment.py", line 693, in <module>
    final_info, train_info, val_info = train(dataset, out_dir, seed_offset)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deepaklenka/sakana/AI-Scientist/templates/nanoGPT/experiment.py", line 552, in train
    logits, loss = model(X, Y)
                   ^^^^^^^^^^^
...
[Include the full traceback]
...
KeyboardInterrupt

End of training: [Insert date and time here]

Additional Notes:
- Training was performed on CPU (MacBook Air)
- Training was interrupted at iteration 2020
- No checkpoint files were saved due to the interruption